USE [DMAP_JIT_Permissions]
GO

/****** Object:  Table [JITA].[PIM_DB_Rollen_HT]    Script Date: 25-11-2025 14:05:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [JITA].[PIM_DB_Rollen_HT](
	[DVK_PIM_DB_Rollen_HT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PIM_ROL_ID] [bigint] NOT NULL,
	[PIM_ROL_Voided] [bit] NULL,
	[DB_ROL_ID] [bigint] NOT NULL,
	[DB_ROL_Voided] [bit] NULL,
	[CreatedBy] [nvarchar](255) NULL,
	[ChangedBy] [nvarchar](255) NULL,
	[DVA_Voided] [bit] NOT NULL,
	[DVA_Recent] [bit] NOT NULL,
	[DVA_BeginDatum] [datetime] NOT NULL,
	[DVA_EindDatum] [datetime] NOT NULL,
	[DVA_InsertDate] [datetime] NOT NULL,
 CONSTRAINT [PK_JITA_PIM_DB_Rollen_HT] PRIMARY KEY NONCLUSTERED 
(
	[DVK_PIM_DB_Rollen_HT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [Indexen]
) ON [PRIMARY]
GO

/****** Object:  Index [JITA_PIM_DB_Rollen_HT_CCI]    Script Date: 25-11-2025 14:05:03 ******/
CREATE CLUSTERED COLUMNSTORE INDEX [JITA_PIM_DB_Rollen_HT_CCI] ON [JITA].[PIM_DB_Rollen_HT] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0, DATA_COMPRESSION = COLUMNSTORE) ON [PRIMARY]
GO


