USE [DMAP_JIT_Permissions]
GO

/****** Object:  Table [JITA].[Rechten]    Script Date: 16-12-2025 10:52:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[JITA].[Rechten]') AND type in (N'U'))
DROP TABLE [JITA].[Rechten]
GO

/****** Object:  Table [JITA].[Rechten]    Script Date: 16-12-2025 10:52:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [JITA].[Rechten](
	[Rechten_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[User] [nvarchar](255) NOT NULL,
	[PIM_ROL_ID] [nvarchar](255) NOT NULL,
	[Relatie_PIM_ROL_ID] [bigint] NOT NULL,
	[AanvraagItem_ID] [bigint] NOT NULL,
	[StartDatum] [datetime] NULL,
	[EindDatum] [datetime] NULL,
	[Sys_EditedBy] [nvarchar](255) NULL,
	[Sys_InsertDate][datetime] NULL,
 CONSTRAINT [PK_JITA_Rechten] PRIMARY KEY NONCLUSTERED 
(
	[Rechten_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [Indexen],

 CONSTRAINT [UNQ_JITA_Rechten] UNIQUE NONCLUSTERED 
(
	[User] ASC,
	[PIM_Rol_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [Indexen]
) ON [PRIMARY]
GO

/****** Object:  Index [JITA_Rechten_CCI]    Script Date: 16-12-2025 10:52:17 ******/
CREATE CLUSTERED COLUMNSTORE INDEX [JITA_Rechten_CCI] ON [JITA].[Rechten] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0, DATA_COMPRESSION = COLUMNSTORE) ON [PRIMARY]
GO


